### ISSUE TITLE
Create tags/releases again

### ISSUE THREAD

**Issue by ahkok** [zeromq/php-zmq#211] opened 2020-03-04 17:41 UTC
current latest release is 1.1.3 and years old (on pecl). There are no new tags in this repo.

I suggest getting back on the rails with tags in this repo. But it would be nice if releases to pecl could be made again as well.

**Comment by bluca** [comment] 2020-03-05 15:21
This repository is without a maintainer, we are looking for one https://lists.zeromq.org/pipermail/zeromq-dev/2019-August/033109.html
Until someone volunteers, there will be no releases

**Comment by bluca** [comment] 2020-03-05 15:22
duplicate of https://github.com/zeromq/php-zmq/issues/203

**Closed by bluca** 2020-03-05 15:22 UTC
